name: LunaHusky
favicon: null
layout_spectrum: 0.25332
typography_spectrum: 0.08504086476750672
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2e29'
    - '#749fcc'
    - '#fcfcfc'
    - '#c29e7c'
    - '#ecce9c'
  brandStrength: 0.75
  lightness: 0.6338749947026372
  saturation: 0.9144786552060395
  rhythmicContrast: 0.13110287906602025
purpose: []
