name: LunaHusky
favicon: null
layout_spectrum: 0.25332
typography_spectrum: 0.87202
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2e29'
    - '#749fcc'
    - '#fcfcfc'
    - '#c29e7c'
    - '#ecce9c'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
